"""change model

Revision ID: e6b1287ce009
Revises: c4e4c8cb4c86
Create Date: 2024-08-29 17:02:45.550495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b1287ce009'
down_revision: Union[str, None] = 'c4e4c8cb4c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refresh_tokens', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
